language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  - rustup component add clippy rustfmt

script:
  - cargo test --release --all --verbose
  - cargo clippy --all
  - cargo fmt -- --check

env:
  global:
  - RUSTFLAGS="-D warnings"
