language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add clippy-preview

script:
  - cargo test --release --all
  - cargo clippy --all

env:
  global:
  - RUSTFLAGS="-D warnings"
