[package]
name = "rust-schreier"
version = "0.1.0"
authors = ["koba-e964 <3303362+koba-e964@users.noreply.github.com>"]
edition = "2021"
publish = false

[dependencies]
num-bigint = "0.4"
rand = "0.8"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "schreier_bench"
harness = false
